## Data 118, Winter 2024, University of Chicago
# Homework 1: Strings, Expressions and Arrays (50 points)

Please complete this notebook by filling in the cells provided.

The solved homework should be uploaded to Gradescope as an .ipynb file. DO NOT put your answers in more than one file or use a different file extension.

Make sure to RUN ALL CELLS IN YOUR NOTEBOOK before submitting. All of your answers should be printed and easy for graders to find if you want full credit for your work.

#### Deadline:

This assignment is due on **Friday, Jan 12th at 11:59pm**. Late work will not be accepted unless it follows the specific policy of your instructor.

Directly sharing answers is not okay, but discussing problems with the course instructors and staff is encouraged, and with other students is allowed.

You should start early so that you have time to get help if you're stuck.

In [ ]:
import numpy as np 
import pandas as pd

In [1]:
# Don't change this cell; just run it.

import numpy as np

## 1. Strings (16 points)

**Question 1. (2 pts)** Use the `replace()` function for strings to change the string *'machine learning'* into the string *'learning machine'*. You must do everything into one line of code and you can only replace one full word with a different full word. An example of using `replace()` twice in one line of code is below. [Note: the output should be a string of the same length as the one you started with; no extra spaces etc.]

In [151]:
# this cell illustrates the use of .replace
'Today is a good day.'.replace('.','!')

'Today is a good day!'

In [152]:
# this cell illustrates the use of .replace twice
'on campus'.replace('on','happy').replace('campus','place')

'happy place'

In [153]:
#Q1 answer here
'machine learning'.replace('machine', 'word').replace('learning', 'machine').replace('word', 'learning')

'learning machine'

Here is a short poem from Shel Silverstein's *Where the Sidewalk Ends*.
Note that the string 'chicken' contains newline characters, which we would like to get rid of.

In [154]:
chicken = '''Oh I am a chicken who lives in an egg, 
But I will not hatch, I will not hatch.
The hens they all cackle, the roosters all beg,
But I will not hatch, I will not hatch.
For I hear all the talk of pollution and war
As the people all shout and the airplanes roar,
So I’m staying in here where it’s safe and it’s warm,
And I WILL NOT HATCH!'''

In [155]:
chicken

'Oh I am a chicken who lives in an egg, \nBut I will not hatch, I will not hatch.\nThe hens they all cackle, the roosters all beg,\nBut I will not hatch, I will not hatch.\nFor I hear all the talk of pollution and war\nAs the people all shout and the airplanes roar,\nSo I’m staying in here where it’s safe and it’s warm,\nAnd I WILL NOT HATCH!'

**Question 2. (2 pts)** Using `str.replace()` and `chicken` from above, create a string called `stanza_oneline` with all the newlines replaced by spaces.

In [156]:
#Q2 Answer
stanza_oneline = str.replace(chicken, '\n', ' ')
stanza_oneline

'Oh I am a chicken who lives in an egg,  But I will not hatch, I will not hatch. The hens they all cackle, the roosters all beg, But I will not hatch, I will not hatch. For I hear all the talk of pollution and war As the people all shout and the airplanes roar, So I’m staying in here where it’s safe and it’s warm, And I WILL NOT HATCH!'

**Question 3. (4 pts)**  Write python expressions that count the number of words and the number of sentences in `stanza_oneline`.  (**Hint**:  Check your answer. If your expression gives the wrong answer, fix your expression.)

In [157]:
#Q3 Answer part 1
number_words = len(stanza_oneline.split(" "))
number_words

73

In [158]:
#Q3 Answer part 2
number_sentences = stanza_oneline.count('.') + stanza_oneline.count('!')
number_sentences

3

The *split* command breaks a string into a list of strings by a specified separator. Also recall that numbers in square braces access elements in a list "slicing" by number.  Below is an example of using the `split()` command, list slicing, and the string concatenation using + to execute the following: from the string *'learning is done by machine'* obtain the string '*machine learning'*.

In [159]:
mystring = "learning is done by machine"
mynewstring = mystring.split()[4] + " " + mystring.split()[0]
mynewstring

'machine learning'

In [2]:
mystring1 = 'Why do we have to do this? Is this going to be on the test?'


**Question 4. (5 pts)**   The string `mystring1` is introduced in the cell above. Build the string "This is on the test." from the parts of `mystring1.split()`, and add/remove any capitalization or punctuation as needed. 


In [3]:
# Q4 answer here
mynewstring1 = "T" + mystring1.split()[6][1:4] + " " + mystring1.split()[6][2] \
    + mystring1.split()[7][1] + " " + mystring1.split()[-3] + " " + \
    mystring1.split()[-2] + " " + mystring1.split()[-1][0:4] + "."
mynewstring1

'This is on the test.'

**Question 5. (1 pt)** Make a list called `phrases` containing the following three strings: "Rachel Ray finds inspiration in cooking", "her family", "and her dog"

In [162]:
# Q5 answer here
phrases = ['Rachel Ray finds inspiration in cooking', 'her family', 'and her dog']
phrases

['Rachel Ray finds inspiration in cooking', 'her family', 'and her dog']

Strings have a method called `join`.  `join` takes one argument, a list of strings.  It returns a single string.  Specifically, the value of `a_string.join(a_list)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `a_list`, **except** `a_string` is inserted in between each string

**Question 6. (2 pts)** Use the list `phrases` and the method `join` to make two strings:

1. "Rachel Ray finds inspiration in cooking, her family, and her dog" (call this one `with_commas`)
2. "Rachel Ray finds inspiration in cooking her family and her dog" (call this one `without_commas`)

In [163]:
# Q6 answer here
with_commas = ", ".join(phrases)
without_commas = " ".join(phrases)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Rachel Ray finds inspiration in cooking, her family, and her dog
without_commas: Rachel Ray finds inspiration in cooking her family and her dog


Note: This headline was printed 'without_commas' in [Tails magazine!](https://themayhew.org/tails-magazine/)

## 2. Names and Assignment Statements (7 points)

Python sometimes gives you difficult-to-get-used-to error messages.

In [164]:
# assign four new variables with unsurprising values
one, two, three, four = 1,2,3,4

**Question 7. (1 pt)**
What happens when we run this expression?  (You may want to check the python documentation under the heading "Operator precedence" https://docs.python.org/3/reference/expressions.html#operator-precedence for the order-of-operations hierarchy in python.)

In [4]:
result = 4 + two == 6

NameError: name 'two' is not defined

Choose the best explanation of what this cell does and put your answer (a, b, c, or d) in the cell below.

&emsp;a. Add 4 and two, store the result in 'result' and compare this to the value 6

&emsp;b. Compare two and 6 (False), add 4, and store the sum in 'result'

&emsp;c. Add 4 and two, compare to 6, and store the comparison in 'result'

&emsp;d. Generates an error because 'result' is not defined.

Answer to Q7 is: C

**Question 8. (1 pt)** When you run the following cell, Python produces a cryptic error message.

In [166]:
4=2+2

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (339577835.py, line 1)

Choose the best explanation of what's wrong with the code, and put your answer (a, b, c, or d) in the cell below.

a. Python is smart and already knows `4 = 2 + 2`.

b. `4` is a number, and it doesn't make sense to make a number be a name for something else. In Python, "`x = 2 + 2`" means "assign `x` as the name for the value of `2 + 2`."

c. It should be `2 + 2 = 4`.

d. I don't get an error message. This is a trick question.

Answer to Q8 is: B

**Question 9. (1 pt)** Choose the best explanation of what's wrong with the code in the cell below and put your answer (a, b, c, or d) in the cell below.


In [ ]:
number = 2 + six

NameError: name 'six' is not defined

a. The + operation only applies to numbers, not the word `six`.

b. `six` is not defined.

c. "=" is the assignment operator, not the test-for-equality operator, which is "==".

d. `+` is not a binary operator.

Answer to Q9 is: B

**Question 10. (4 pt)** Name 2 common error types in Python and give examples of code that would produce each error (the code should be based on topics you've learned so far!) *Hint:* You may need to use Google.

Q10 Error 1:

In [5]:
# Q10 error 1 answer code
# TypeError
fruit = ['apple', 'banana', 'grape']
result = fruit / 3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Q10 Error 2:

In [ ]:
# Q10 error 1 answer code
# SyntaxError
message = 'This is a syntax error
print(message)

SyntaxError: unterminated string literal (detected at line 2) (280030569.py, line 2)

## 3. Mathematical Operations (14 points)

**Question 11. (1 pt)** Compute the fifth root of 12 using code. (You might have to investigate online how to do this. Reminder, Google is your friend when investigating built in methods and functions in Python!)

In [ ]:
# Q11 answer code
fifth_root_twelve = np.power(12, 1/5)
fifth_root_twelve

1.6437518295172258

**Question 12. (2 pts)** You can use NumPy's ```np.pi``` to use pi in any mathematical computation! Round pi to the 8th decimal place using code. NOTE: Here 8 decimal places means 8 digits after the decimal. For instance, pi rounded to 2 decimal place is 3.14

In [ ]:
# Q12 answer code
pi = round(np.pi, 8)
pi

3.14159265

**Question 13. (4 pts)** In the next cell, make an array called `weird_numbers` containing the following numbers (in the given order):

1. -9.5
2. the tangent of 2.11
3. 67
4. 3 to the power of the sine of 1.6

*Hint:* `sin` and `tan` are functions in the `math` module. You need to import the module first!

In [ ]:
# Q13 answer code
import math
number_list = [-9.5, math.tan(2.11), 67, 3 ** math.sin(1.6)]
weird_numbers = np.array(number_list)
weird_numbers


array([-9.5       , -1.67126912, 67.        ,  2.99859499])

**Question 14. (4 pts)** Finish the code in the following cell so that it calculates the volume of a sphere of radius 10, and it prints **"Volume of a sphere of radius 10 is ?"** (with "?" replace by the correct answer).

In [ ]:
# Q14 answer code
pi = np.pi
r = 10
V = (4/3) * pi * r ** 3
print('Volume of a sphere with radius 10 is', V)
V

Volume of a sphere with radius 10 is 4188.790204786391


4188.790204786391

**Question 15. (3 pts)** A certain device was made by casting and machining 6.46 kg of plutonium alloy into the shape of a sphere.  The alloy has a density of 15.6 g / cm$^3$.  What is the diameter of the sphere if the sphere is solid?

**Hint:** use algebra to find `r` as a function of `V`, then implement your expression in python.

<img width=150 src=https://upload.wikimedia.org/wikipedia/commons/1/13/Partially-reflected-plutonium-sphere.jpeg>


**Hint:** A photograph of the sphere is above with a ruler in inches nearby; image is at https://upload.wikimedia.org/wikipedia/commons/1/13/Partially-reflected-plutonium-sphere.jpeg

In [ ]:
#Q15 Answer code
Volume = 6460/15.6
diameter = 2 * np.power((Volume * (3 / 4)) / np.pi, 1 / 3)
diameter

9.247757490131361

## 4.  Arrays Indexing and Arithmetic (13 points)

These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.  

**Question 16. (1 pt)** The cell below creates an array of some numbers.  Set `fifth_element` to the fifth element of `some_numbers`.

In [ ]:
#Q16 Answer code
some_numbers = np.array([1,1,2,3,5,8,13,21])

fifth_element = some_numbers[4]
fifth_element

5

**Question 17. (3 pts)** We can convert from feet to meters by multiplying by 0.3048. Multiply the numbers 243, 569, 577, 580, 600, and 611 by 0.3048 to convert them from feet to meters. For this question, **don't** use arrays.

In [ ]:
#Q17 Answer code
first_product = 243 * 0.3048
second_product = 569 * 0.3048
third_product = 577 * 0.3048
fourth_product = 580 * 0.3048
fifth_product = 600 * 0.3048
sixth_product = 611 * 0.3048

print(first_product, second_product, third_product, fourth_product, fifth_product, sixth_product)

74.0664 173.43120000000002 175.86960000000002 176.78400000000002 182.88 186.2328


**Question 18. (2 pts)** Now, do the same calculation, but using an array called `elevations_ft` (that will contain the numbers above) and only a single multiplication (`*`) operator.  Store the 6 results in an array named `elevations_m`.

In [ ]:
#Q18 answer code
elevations_ft = np.array([243, 569, 577, 580, 600, 611])
elevations_m = elevations_ft * 0.3048
elevations_m

array([ 74.0664, 173.4312, 175.8696, 176.784 , 182.88  , 186.2328])

**Question 19. (7 pts)** In the following questions, you will apply some built-in Numpy functions to the array named `elevations_m`. It is useful to refer to the documentation when investigating new functions! See [documentation here:](https://numpy.org/doc/stable/reference/routines.math.html)

**a. (2 pts)** Use Numpy's cumulative sum function on the array and explain what the function does. Note, do not just copy the documentation, explain what the function does in context of the problem.

In [ ]:
# Q19a answer code
# Starting at index 0 (first element) and on, this function creates a new array 
# containing cumulative sums of elevation corresponding to the original array.
# The index of each cumulative sum matches with the index of the last added 
# number of that sum from the original array.
cumsum_elevations_m = np.cumsum(elevations_m)
cumsum_elevations_m


array([ 74.0664, 247.4976, 423.3672, 600.1512, 783.0312, 969.264 ])

Answer to Q19a is:

**b. (2 pts)** Use Numpy to find the natural logarithm of each value in the array.

In [ ]:
# Q19b answer code
nlog_elevations_m = np.log(elevations_m)
nlog_elevations_m


array([4.30496199, 5.15578098, 5.16974281, 5.17492865, 5.2088302 ,
       5.2269975 ])

**c. (1 pts)** Use Numpy to calculate the median of the values in the array

In [ ]:
#Q19c answer code
median = np.median(elevations_m)
median

176.32680000000002

**d. (2 pts)** What is the default sorting algorithm used by `np.sort`? Which sorting algorithm used by `np.sort` is the slowest?

Answer to Q19d is:

In [ ]:
# The default sorting is 'quicksort'
sorted_elevations_m = np.sort(elevations_m)
sorted_elevations_m

# 'heapsort' is the slowest


array([ 74.0664, 173.4312, 175.8696, 176.784 , 182.88  , 186.2328])